apply command: command line parser

diff --git a/chez b/chez
--- a/chez
+++ b/chez
@@ -53,10 +53,59 @@ function command_git()
   exit 0
 }
 
+function apply_single_path()
+{
+  echo "Applying $1..."
+  return 0
+}
+
 function command_apply()
 {
-  echo command_apply: done
-  exit 0
+  local option_symbolic=""
+  local option_force=""
+  local success_cnt=0 failure_cnt=0
+
+  shift
+  while [[ $# -gt 0 ]]; do
+    if [[ "$1" == "-s" ]]; then
+      option_symbolic="yes"
+    elif [[ "$1" == "-c" || "$1" == "--copy" ]]; then
+      option_symbolic="no"
+    elif [[ "$1" == "-f" || "$1" == "--force" ]]; then
+      option_force="yes"
+    elif [[ "$1" != -* ]]; then
+      apply_single_path "$1" && (( ++success_cnt )) || (( ++failure_cnt ))
+    else
+      perror "unknown option $1"
+    fi
+    shift
+  done
+
+  if (( $success_cnt == 0 )) && (( $failure_cnt == 0 )); then
+    apply_single_path "${REPOSITORY_DIR}/Files"
+  elif (( $failure_cnt > 0 && $failure_cnt+$success_cnt > 1)); then
+    echo "$((success_cnt+failure_cnt)) paths applied: $success_cnt success(es), $failure_cnt failure(s)"
+  fi
+
+  (( failure_cnt == 0 ))
+  exit $?
+}
+
+function command_apply_check_options()
+{
+  shift
+  while [[ $# -gt 0 ]]; do
+    case "$1" in
+      -s) ;&
+      -c) ;&
+      -f|--force) : ;;
+      *)
+        if [[ "$1" == -* ]]; then
+          perror "unknown option $1"
+	fi ;;
+    esac
+    shift
+  done
 }
 
 function ensure_repository_exists()
@@ -254,6 +303,7 @@ while [[ $# -gt 0 ]]; do
       command_add_check_options "$@"
       command_add "$@"    ;;
     apply)
+      command_apply_check_options "$@"
       command_apply "$@"  ;;
     diff)
       command_diff "$@"   ;;
